on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  buidMacOS:
    name: build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  buidIOS:
    name: build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun -sdk iphonesimulator -show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios11.0-simulator"

  buidTVOS:
    name: build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun -sdk appletvsimulator -show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos11.0-simulator"
